#!/bin/bash

# Minimal PostgreSQL startup script with full paths
#
# NOTE: The Kavia container platform expects this database to be reachable on port 3002.
# The container's .env sets PGPORT=3002, but this script previously hard-coded DB_PORT=5000,
# causing the readiness check on 3002 to fail.
DB_NAME="myapp"
DB_USER="appuser"
DB_PASSWORD="dbuser123"

# Prefer environment-configured port (PGPORT/POSTGRES_PORT), fall back to legacy default.
DB_PORT="${PGPORT:-${POSTGRES_PORT:-3002}}"

echo "Starting PostgreSQL setup..."

# Find PostgreSQL version and set paths
PG_VERSION=$(ls /usr/lib/postgresql/ | head -1)
PG_BIN="/usr/lib/postgresql/${PG_VERSION}/bin"

echo "Found PostgreSQL version: ${PG_VERSION}"

# Check if PostgreSQL is already running on the specified port
if sudo -u postgres ${PG_BIN}/pg_isready -p ${DB_PORT} > /dev/null 2>&1; then
    echo "PostgreSQL is already running on port ${DB_PORT}!"
    echo "Database: ${DB_NAME}"
    echo "User: ${DB_USER}"
    echo "Port: ${DB_PORT}"
    echo ""
    echo "To connect to the database, use:"
    echo "psql -h localhost -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}"
    
    # Check if connection info file exists
    if [ -f "db_connection.txt" ]; then
        echo "Or use: $(cat db_connection.txt)"
    fi
    
    echo ""
    echo "Script stopped - server already running."
    exit 0
fi

# Also check if there's a PostgreSQL process running (in case pg_isready fails)
if pgrep -f "postgres.*-p ${DB_PORT}" > /dev/null 2>&1; then
    echo "Found existing PostgreSQL process on port ${DB_PORT}"
    echo "Attempting to verify connection..."
    
    # Try to connect and verify the database exists
    if sudo -u postgres ${PG_BIN}/psql -p ${DB_PORT} -d ${DB_NAME} -c '\q' 2>/dev/null; then
        echo "Database ${DB_NAME} is accessible."
        echo "Script stopped - server already running."
        exit 0
    fi
fi

# Initialize PostgreSQL data directory if it doesn't exist
if [ ! -f "/var/lib/postgresql/data/PG_VERSION" ]; then
    echo "Initializing PostgreSQL..."
    sudo -u postgres ${PG_BIN}/initdb -D /var/lib/postgresql/data
fi

# Ensure data directory permissions are correct (initdb normally sets these, but be defensive)
sudo mkdir -p /var/lib/postgresql/data
sudo chown -R postgres:postgres /var/lib/postgresql/data
sudo chmod 700 /var/lib/postgresql/data 2>/dev/null || true

# Create a minimal, explicit config overlay to ensure the server actually binds to TCP :${DB_PORT}
# (Some environments default to unix-socket-only, which will fail port-based readiness checks.)
CONF_DIR="/var/lib/postgresql/data"
CUSTOM_CONF="${CONF_DIR}/postgresql.conf"
CUSTOM_HBA="${CONF_DIR}/pg_hba.conf"

if [ ! -f "${CUSTOM_CONF}" ]; then
    echo "Creating ${CUSTOM_CONF} with explicit port/listen settings..."
    sudo -u postgres tee "${CUSTOM_CONF}" > /dev/null << EOF
# Auto-generated by startup.sh for Kavia container runtime.
# Keep minimal and explicit so readiness checks work reliably.
listen_addresses = '*'
port = ${DB_PORT}

# Reasonable defaults for containers
max_connections = 100
shared_buffers = 128MB

# Make logs visible in container stdout/stderr (postgres may still log to stderr depending on build)
logging_collector = off
EOF
fi

if [ ! -f "${CUSTOM_HBA}" ]; then
    echo "Creating ${CUSTOM_HBA} to allow local and in-cluster connections..."
    sudo -u postgres tee "${CUSTOM_HBA}" > /dev/null << 'EOF'
# Auto-generated by startup.sh
# "local" is for unix socket connections only
local   all             all                                     trust

# IPv4 / IPv6 local connections:
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Allow connections from any address (typical for container networks).
# Use scram-sha-256 if available; fall back is handled by postgres if not supported.
host    all             all             0.0.0.0/0               scram-sha-256
EOF
fi

# Start PostgreSQL server in background with explicit config + hba file + port.
echo "Starting PostgreSQL server on port ${DB_PORT}..."
sudo -u postgres ${PG_BIN}/postgres \
  -D /var/lib/postgresql/data \
  -c "config_file=${CUSTOM_CONF}" \
  -c "hba_file=${CUSTOM_HBA}" \
  -c "listen_addresses=*" \
  -c "port=${DB_PORT}" &

# Wait for PostgreSQL to start (explicitly check TCP localhost)
echo "Waiting for PostgreSQL to start..."
sleep 2

# Check if PostgreSQL is running
for i in {1..20}; do
    if sudo -u postgres ${PG_BIN}/pg_isready -h 127.0.0.1 -p ${DB_PORT} > /dev/null 2>&1; then
        echo "PostgreSQL is ready on 127.0.0.1:${DB_PORT}!"
        break
    fi
    echo "Waiting... ($i/20)"
    sleep 1
done

# Create database and user
echo "Setting up database and user..."
sudo -u postgres ${PG_BIN}/createdb -p ${DB_PORT} ${DB_NAME} 2>/dev/null || echo "Database might already exist"

# Set up user and permissions with proper schema ownership
sudo -u postgres ${PG_BIN}/psql -p ${DB_PORT} -d postgres << EOF
-- Create user if doesn't exist
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_USER}') THEN
        CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASSWORD}';
    END IF;
    ALTER ROLE ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
END
\$\$;

-- Grant database-level permissions
GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};

-- Connect to the specific database for schema-level permissions
\c ${DB_NAME}

-- For PostgreSQL 15+, we need to handle public schema permissions differently
-- First, grant usage on public schema
GRANT USAGE ON SCHEMA public TO ${DB_USER};

-- Grant CREATE permission on public schema
GRANT CREATE ON SCHEMA public TO ${DB_USER};

-- Make the user owner of all future objects they create in public schema
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO ${DB_USER};

-- If you want the user to be able to create objects without restrictions,
-- you can make them the owner of the public schema (optional but effective)
-- ALTER SCHEMA public OWNER TO ${DB_USER};

-- Alternative: Grant all privileges on schema public to the user
GRANT ALL ON SCHEMA public TO ${DB_USER};

-- Ensure the user can work with any existing objects
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_USER};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${DB_USER};
EOF

# Additionally, connect to the specific database to ensure permissions
sudo -u postgres ${PG_BIN}/psql -p ${DB_PORT} -d ${DB_NAME} << EOF
-- Double-check permissions are set correctly in the target database
GRANT ALL ON SCHEMA public TO ${DB_USER};
GRANT CREATE ON SCHEMA public TO ${DB_USER};

-- Show current permissions for debugging
\dn+ public
EOF

# Save connection command to a file
echo "psql postgresql://${DB_USER}:${DB_PASSWORD}@localhost:${DB_PORT}/${DB_NAME}" > db_connection.txt
echo "Connection string saved to db_connection.txt"

# Save environment variables to a file
cat > db_visualizer/postgres.env << EOF
export POSTGRES_URL="postgresql://localhost:${DB_PORT}/${DB_NAME}"
export POSTGRES_USER="${DB_USER}"
export POSTGRES_PASSWORD="${DB_PASSWORD}"
export POSTGRES_DB="${DB_NAME}"
export POSTGRES_PORT="${DB_PORT}"
EOF

echo "PostgreSQL setup complete!"
echo "Database: ${DB_NAME}"
echo "User: ${DB_USER}"
echo "Port: ${DB_PORT}"
echo ""

echo "Environment variables saved to db_visualizer/postgres.env"
echo "To use with Node.js viewer, run: source db_visualizer/postgres.env"

echo "To connect to the database, use one of the following commands:"
echo "psql -h localhost -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT}"
echo "$(cat db_connection.txt)"
